SLEEP_LED_ENABLE     = no
DEBUG_ENABLE         = no
CONSOLE_ENABLE       = no
TAP_DANCE_ENABLE     = yes
MOUSEKEY_ENABLE      = yes
NKRO_ENABLE          = yes
EXTRAKEY_ENABLE      = yes          # Audio control and System control
BACKLIGHT_ENABLE     = no
VISUALIZER_ENABLE    = no
LCD_BACKLIGHT_ENABLE = no
LCD_ENABLE           = yes
UNICODE_ENABLE	     = yes
